
"use strict";
const sb=window.supabase.createClient(APP_CONFIG.SUPABASE_URL,APP_CONFIG.SUPABASE_PUBLISHABLE_KEY),$=s=>document.querySelector(s),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));let faqs=[];
function status(t,b=false){$("#status").innerHTML=`<div class="status${b?" bad":""}">${esc(t)}</div>`}
async function view(){const {data:{session}}=await sb.auth.getSession();$("#loginBox").classList.toggle("hidden",!!session);$("#adminBox").classList.toggle("hidden",!session);if(session)load()}
$("#loginBtn").onclick=async()=>{const {error}=await sb.auth.signInWithPassword({email:$("#loginEmail").value.trim(),password:$("#loginPassword").value});if(error)$("#loginStatus").innerHTML=`<div class="status bad">${esc(error.message)}</div>`;else view()};
$("#logoutBtn").onclick=async()=>{await sb.auth.signOut();view()};$("#viewSite").onclick=()=>location.href="/";
async function load(){const [s,f]=await Promise.all([sb.from("studio_settings").select("*").eq("id",1).single(),sb.from("faqs").select("*").order("sort_order").order("id")]);if(s.error||f.error){status(s.error?.message||f.error?.message,true);return}const x=s.data;$("#studioName").value=x.studio_name||"";$("#phone").value=x.phone||"";$("#email").value=x.email||"";$("#address").value=x.address||"";faqs=f.data||[];render()}
$("#saveSettings").onclick=async()=>{const {error}=await sb.from("studio_settings").update({studio_name:$("#studioName").value.trim(),phone:$("#phone").value.trim(),email:$("#email").value.trim(),address:$("#address").value.trim()}).eq("id",1);status(error?error.message:"Dati aggiornati.",!!error)};
function render(){$("#faqList").innerHTML=faqs.map(x=>`<div class="itemEditor" data-id="${x.id}"><div class="row"><div class="field"><label>Categoria</label><input class="category" value="${esc(x.category)}"></div><div class="field"><label>Icona</label><input class="icon" value="${esc(x.icon||"📌")}"></div></div><div class="field"><label>Domanda</label><input class="questionInput" value="${esc(x.question)}"></div><div class="field"><label>Risposta</label><textarea class="answerInput">${esc(x.answer)}</textarea></div><div class="row"><div class="field"><label>Ordine</label><input class="sortOrder" type="number" value="${x.sort_order||0}"></div><div class="field"><label>Pubblicata</label><select class="published"><option value="true"${x.published?" selected":""}>Sì</option><option value="false"${!x.published?" selected":""}>No</option></select></div></div><div class="row"><button class="btn primary saveFaq">Salva</button><button class="btn danger deleteFaq">Elimina</button></div></div>`).join("");document.querySelectorAll(".saveFaq").forEach(b=>b.onclick=()=>save(b.closest(".itemEditor")));document.querySelectorAll(".deleteFaq").forEach(b=>b.onclick=()=>del(b.closest(".itemEditor")))}
async function save(el){const {error}=await sb.from("faqs").update({category:el.querySelector(".category").value.trim(),icon:el.querySelector(".icon").value.trim(),question:el.querySelector(".questionInput").value.trim(),answer:el.querySelector(".answerInput").value.trim(),sort_order:Number(el.querySelector(".sortOrder").value)||0,published:el.querySelector(".published").value==="true"}).eq("id",Number(el.dataset.id));status(error?error.message:"FAQ aggiornata.",!!error);if(!error)load()}
async function del(el){if(!confirm("Eliminare?"))return;const {error}=await sb.from("faqs").delete().eq("id",Number(el.dataset.id));status(error?error.message:"FAQ eliminata.",!!error);if(!error)load()}
$("#newFaq").onclick=async()=>{const {error}=await sb.from("faqs").insert({category:"Nuova categoria",icon:"📌",question:"Nuova domanda",answer:"Nuova risposta",sort_order:999,published:false});status(error?error.message:"FAQ creata.",!!error);if(!error)load()};view();
