
"use strict";
const sb=window.supabase.createClient(APP_CONFIG.SUPABASE_URL,APP_CONFIG.SUPABASE_PUBLISHABLE_KEY);
const q=document.getElementById("question"),messages=document.getElementById("messages"),categories=document.getElementById("categories");
let faqs=[];const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
function msg(text,type="bot",sources=[]){const d=document.createElement("div");d.className="msg "+type;d.innerHTML=`<div class="bubble">${esc(text)}${sources.length?`<div class="sources">Fonti: ${sources.map(esc).join(" · ")}</div>`:""}</div>`;messages.appendChild(d);d.scrollIntoView({behavior:"smooth",block:"end"})}
function render(){const cats=[...new Map(faqs.map(x=>[x.category,{category:x.category,icon:x.icon||"📌"}])).values()];categories.innerHTML=`<div class="grid">${cats.map(c=>`<button class="cat" data-cat="${esc(c.category)}"><div class="icon">${esc(c.icon)}</div><strong>${esc(c.category)}</strong><span>${faqs.filter(x=>x.category===c.category).length} risposte</span></button>`).join("")}</div><div id="faqResults" class="panel"></div>`;document.querySelectorAll(".cat").forEach(b=>b.onclick=()=>{const rows=faqs.filter(x=>x.category===b.dataset.cat);document.getElementById("faqResults").innerHTML=rows.map(x=>`<div class="faq"><button class="question"><span>${esc(x.question)}</span><span>＋</span></button><div class="answer">${esc(x.answer)}</div></div>`).join("");document.querySelectorAll(".question").forEach(x=>x.onclick=()=>x.closest(".faq").classList.toggle("open"))})}
async function load(){const [s,f]=await Promise.all([sb.from("studio_settings").select("*").eq("id",1).maybeSingle(),sb.from("faqs").select("*").eq("published",true).order("sort_order")]);if(s.data){document.getElementById("studioTitle").textContent=s.data.studio_name;document.getElementById("callLink").href="tel:"+(s.data.phone||"").replace(/\s/g,"");document.getElementById("mailLink").href="mailto:"+(s.data.email||"")}faqs=f.data||[];render();msg("Buongiorno. Rispondo soltanto usando le informazioni approvate dallo studio.")}
async function ask(){const text=q.value.trim();if(!text)return;msg(text,"user");q.value="";try{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:text})});const j=await r.json();if(!r.ok)throw new Error(j.error);msg(j.answer,"bot",j.sources||[])}catch{msg("Non riesco a elaborare la richiesta. Contatta direttamente lo studio.")}}
document.getElementById("ask").onclick=ask;q.onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();ask()}};load();
